param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "C:\Program Files\IAR Systems\Embedded Workbench 9.2\common\bin\cspybat" -f "D:\D盘桌面\单片机相关\0越野相关\【例程】各个模块的使用例程\E01_01_button_switch_demo\iar\project_config\settings\cyt4bb7_cm_0_plus.Debug.general.xcl" --backend -f "D:\D盘桌面\单片机相关\0越野相关\【例程】各个模块的使用例程\E01_01_button_switch_demo\iar\project_config\settings\cyt4bb7_cm_0_plus.Debug.driver.xcl" 
}
else
{
& "C:\Program Files\IAR Systems\Embedded Workbench 9.2\common\bin\cspybat" -f "D:\D盘桌面\单片机相关\0越野相关\【例程】各个模块的使用例程\E01_01_button_switch_demo\iar\project_config\settings\cyt4bb7_cm_0_plus.Debug.general.xcl" --debug_file=$debugfile --backend -f "D:\D盘桌面\单片机相关\0越野相关\【例程】各个模块的使用例程\E01_01_button_switch_demo\iar\project_config\settings\cyt4bb7_cm_0_plus.Debug.driver.xcl" 
}
